sender: sender0
sender-key: c03e76c81a56f831a1ea91b93545d6b49daffc53c7416e065fcffb025faee47e
network: testnet06
ns-key-1: 434e04bf944f03e8f8b4de1a521a8d04ae99848e11ab2369999cec778e99c30a
ns-key-2: d58b2af9863926f17d6308751a9c491acf3bb02e896c45c912c6a08872310970
util-key-1: 4a577d439b52a26cd5491712bc91ab3fc621bc6dd9f1e794275c3ac453999a2d
util-key-2: 4e838dd36636a74c12e40443e5058f4cbabcd3de7074b5654682338caad210fc
kip-key-1: 025be563698467b6145411ec342fba3c91aa7a2881720fb099d79b089179e137
kip-key-2: 7f9d619365922cdad72dffa150eadfbe7a3897346dcde49308b0b3e78046d7ae
gas-station-key: 1dd2c77318e09e3cb1abab2c5203987a967fa64517a4f436ae360bf9c410429b
allocation00-key: f8a1c425cb65899ae0bf0dd4c6a982554f2ce8914c5084446f4999c3c0019990
allocation01-key: e55612401fb67190d3c0a905749264806a3b66c9b9d048b84b96e120e4a387dc
chain-funder-key: e1c091b53f7431f8f2cb40871a22d83413534340cf60ef4d2bf75b5fa5fee5d0
faucet-key: c5e1c4261f9fa1e16d56cdbb1a87c23af0e183720b7b784dc5d16dc4e87234ff
x-chain-gas-station: kadena-xchain-gas
faucet-funding-amount: 90000.0
chain: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11","12","13","14", "15", "16", "17", "18","19"]